addining tests for Author
MiloszMertka/testing-project pull request #3
Opened 2023-10-27 15:17 UTC by bborkowsp

Cześć,
prośba o przejrzenie kodu.
Dodałem testy dla trzech klas. Być może testy dla AuthorDtoTest i AuthorTest są niepotrzebne, ale z rozpędu już je napisałem.

2023-10-27 15:36 UTC, sebastiangrosfeld commented on src/test/java/com/example/testing/dto/AuthorDtoTest.java
> +    void shouldCorrectly_createAuthorDto() {
do wyjebania, nie testuje się konstruktora

2023-10-27 15:38 UTC, sebastiangrosfeld commented on src/test/java/com/example/testing/dto/AuthorDtoTest.java
zmieniłbym nazwę na AuthorDtoValidationTest

2023-10-27 15:39 UTC, sebastiangrosfeld commented on src/test/java/com/example/testing/model/AuthorTest.java
> +    void shouldCorrectly_createAuthor() {
nie testuje się konstruktora, klasa bez sensu

2023-10-27 15:58 UTC, sebastiangrosfeld commented on src/test/java/com/example/testing/service/internal/AuthorServiceTest.java
> +        AuthorDto authorDto = new AuthorDto(1L, "Adam", "Smith");
użyj id zamiast 1L

2023-10-27 16:16 UTC, sebastiangrosfeld commented on src/test/java/com/example/testing/model/AuthorTest.java
> +    void shouldCorrectly_createAuthor() {
ale możesz tak samo zrobić jak z AuthorDto i zmienić AuthorTest na AuthorValidationTest i przetestować validacje

2023-10-27 16:19 UTC, bborkowsp commented on src/test/java/com/example/testing/dto/AuthorDtoTest.java
> +    void shouldCorrectly_createAuthorDto() {
Ok

2023-10-27 16:21 UTC, bborkowsp commented on src/test/java/com/example/testing/dto/AuthorDtoTest.java
Czy to nie będzie mylące? Raczej przyjmuje się konwencje [NazwaKlasyKtórąTestuje]Test.

2023-10-27 16:22 UTC, bborkowsp commented on src/test/java/com/example/testing/model/AuthorTest.java
> +    void shouldCorrectly_createAuthor() {
Klasa usunięta 
![download](https://github.com/MiloszMertka/testing-project/assets/95755487/5939c0ff-57eb-4a63-8974-8ceeb00e35e7)

2023-10-27 16:23 UTC, bborkowsp commented on src/test/java/com/example/testing/service/internal/AuthorServiceTest.java
> +        AuthorDto authorDto = new AuthorDto(1L, "Adam", "Smith");
![f27bbc61-d100-46de-8ada-93fd92feca6d](https://github.com/MiloszMertka/testing-project/assets/95755487/340d1920-9306-4eba-97b7-46ff8c43ed84)

2023-10-27 16:24 UTC, sebastiangrosfeld reviewed
do poprawy

2023-10-27 16:26 UTC, sebastiangrosfeld commented on src/test/java/com/example/testing/dto/AuthorDtoTest.java
Ale nie testujesz tu samej klasy tylko jej pola, czyli przeprowadzasz tylko validacje pól

2023-10-28 07:03 UTC, MiloszMertka requested changes
Brakuje jeszcze pokrycia klasy AuthorMapperService testami

2023-10-29 09:30 UTC, MiloszMertka approved these changes
Wygląda spoko

2023-10-29 09:30 UTC, merged